export default function HowItWorks() {
  const steps = [
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-16 h-16 mx-auto">
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 18.375a6.375 6.375 0 0 0 6.375-6.375h.038V10.5a8.25 8.25 0 0 0-16.5 0v1.5H2.625A6.375 6.375 0 0 0 9 18.375m3 0V10.5m0 7.875M3 10.5h18M9 18.375a6.375 6.375 0 0 0 3-5.625m3 5.625a6.375 6.375 0 0 1-3-5.625m0 0V10.5m0 2.25V10.5m0 2.25c0 1.804.735 3.46 1.925 4.675M12 12.75c-.665 0-1.285-.144-1.845-.411M9.925 10.5A6.375 6.375 0 0 0 12 12.75m5.075-2.25A6.375 6.375 0 0 1 12 12.75" />
        </svg>
      ),
      title: "1. Spark Your Imagination",
      description: "Receive a unique, quirky prompt generated by our creative AI. Think \"a cat surfing on a rainbow\" or \"a clock melting like ice cream.\""
    },
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-16 h-16 mx-auto">
          <path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
        </svg>
      ),
      title: "2. Sketch Your Vision",
      description: "You get a simple canvas and limited time to bring the AI's vision to life. No artistic skills required – it's all about interpretation!"
    },
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-16 h-16 mx-auto">
          <path strokeLinecap="round" strokeLinejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0-4.5 2.25 2.25 0 0 0 0 4.5Zm0 0H11.55M12.75 6H16.5m0 0V2.25m0 3.75L13.5 4.5M12.75 6v4.5m0 0H8.25m4.5 0L12 12.75M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-18 0L5.25 9.75M18.75 16.5l-3-3.75m0 0L12.75 9.75M12.75 9.75L9.75 12.75" />
        </svg>
      ),
      title: "3. Share & Discover",
      description: "Submit your creation to the public gallery. Browse hilarious and inventive artworks from players worldwide and see how they interpreted similar prompts!"
    }
  ]

  return (
    <section className="py-12 md:py-20 bg-gray-100">
      <div className="container mx-auto px-6">
        <h2 className="text-3xl md:text-4xl font-bold text-center text-gray-900 mb-12">
          How It Works
        </h2>
        <div className="grid md:grid-cols-3 gap-8 text-center">
          {steps.map((step, index) => (
            <div 
              key={index}
              className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300 transform hover:-translate-y-1"
            >
              <div className="text-blue-600 mb-4">
                {step.icon}
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                {step.title}
              </h3>
              <p className="text-gray-600">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}